### ISSUE TITLE
App is crashing in Android 13

### ISSUE THREAD

**Issue by be4zad** [sz3/cfc#27]
ROM: CrDroid 9.0

Logs:
```
time: 1703228651524
msg: java.lang.UnsatisfiedLinkError: No implementation found for void org.cimbar.camerafilecopy.MainActivity.shutdownJNI() (tried Java_org_cimbar_camerafilecopy_MainActivity_shutdownJNI and Java_org_cimbar_camerafilecopy_MainActivity_shutdownJNI__)
stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for void org.cimbar.camerafilecopy.MainActivity.shutdownJNI() (tried Java_org_cimbar_camerafilecopy_MainActivity_shutdownJNI and Java_org_cimbar_camerafilecopy_MainActivity_shutdownJNI__)
	at org.cimbar.camerafilecopy.MainActivity.shutdownJNI(Native Method)
	at org.cimbar.camerafilecopy.MainActivity.onPause(MainActivity.java:118)
	at android.app.Activity.performPause(Activity.java:8466)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1591)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5078)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5039)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4991)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

**Comment by sz3** [comment]
Thanks for reporting this.

It looks like the shared library (C++/NDK) component isn't getting loaded. I'm wondering if there's something interesting/different I need to worry about with CrDroid specifically...

Did you install from fDroid, or the Play Store (or the apk on github?)

**Comment by be4zad** [comment]
f-droid

**Comment by BurningButter** [comment]
Same issue, I also downloaded from f-droid

**Comment by BurningButter** [comment]
I tried to install the APK from github and it said it was incompatible with my phone

**Comment by sz3** [comment]
If either of you are up to run a test, I can produce an experimental build (or two) that *might* help.

Fair warning: it's a shot in the dark, and might not help. But I do have a couple ideas. :thinking:

**Comment by BurningButter** [comment]
I wouldn't mind

**Comment by sz3** [comment]
The simplest theory is that arm7a libraries are needed, so I made a build of 0.6.1 that supports both v7 (32bit) and v8... theoretically.

Anyway, if you try it, let me know if it installs for you. If it works, even better. :slightly_smiling_face: 

(The apk is in a zip because github won't allow direct apk uploads.)
[cfcbeta.zip](https://github.com/sz3/cfc/files/14582520/cfcbeta.zip)

**Comment by be4zad** [comment]
@sz3 url not found

**Comment by sz3** [comment]
Sorry about that, github lied to me. This link should work:
https://cimbar.org/beta/cfc_arm32_0.6.1_cv4.8.apk

**Comment by be4zad** [comment]
@sz3 It's work.

**Comment by be4zad** [comment]
@sz3 It works.

**Comment by sz3** [comment]
\o/

**Comment by BurningButter** [comment]
Worked for me too!
